// This file was generated by DialogueDatabaseAssetEditor.cs. Do not edit!
using UnityEngine;
public static class DialogueDatabase
{
	//TestScene
	public static Vector2Int I2D2 = new Vector2Int(0,0);
	public static Vector2Int M8F6 = new Vector2Int(0,1);
	//BasicsNarration
	public static Vector2Int W4H2 = new Vector2Int(1,0);
	public static Vector2Int M8T4 = new Vector2Int(1,1);
	public static Vector2Int F3C6 = new Vector2Int(1,2);
	public static Vector2Int M7Q2 = new Vector2Int(1,3);
	public static Vector2Int T331 = new Vector2Int(1,4);
	public static Vector2Int T332 = new Vector2Int(1,5);
	public static Vector2Int T333 = new Vector2Int(1,6);
	public static Vector2Int t334 = new Vector2Int(1,7);
	public static Vector2Int t335 = new Vector2Int(1,8);
	public static Vector2Int t336 = new Vector2Int(1,9);
	public static Vector2Int t337 = new Vector2Int(1,10);
	public static Vector2Int s1J1 = new Vector2Int(1,11);
	public static Vector2Int s1J2 = new Vector2Int(1,12);
	public static Vector2Int s1J3 = new Vector2Int(1,13);
	public static Vector2Int s1J4 = new Vector2Int(1,14);
	public static Vector2Int s2K1 = new Vector2Int(1,15);
	public static Vector2Int s2K2 = new Vector2Int(1,16);
	public static Vector2Int s2K3 = new Vector2Int(1,17);
	public static Vector2Int s3L1 = new Vector2Int(1,18);
	public static Vector2Int s3L2 = new Vector2Int(1,19);
	public static Vector2Int s3L3 = new Vector2Int(1,20);
	public static Vector2Int s3L4 = new Vector2Int(1,21);
	public static Vector2Int aLL1 = new Vector2Int(1,22);
	public static Vector2Int aLL2 = new Vector2Int(1,23);
	public static Vector2Int aLL3 = new Vector2Int(1,24);
	public static Vector2Int aLL4 = new Vector2Int(1,25);
	public static Vector2Int aLL5 = new Vector2Int(1,26);
	//JackOutdoors
}
