// This file was generated by ScenumGenerator.cs. Do not edit!
// Since Unity serializes enums as ints, do not expose this to the editor. This is meant to easily switch scenes by build index in code
public static class Scenum
{
	public enum Scene
	{
		InitialScene,
		SampleScene,
		TestLevel,
		BasicPushTutorial,
		FirstLevel,
		OptimizeRoute,
		SwitchTutorial,
		SuperPushTutorial,
		JackAndLaguna,
		TrapSpikePuzzle,
		JackTutorial,
		ThreeLanes,
		ZachsTestLevel,
		MakeABridge,
		MainMenu,
		BlockBlocks,
		MultiPushCorridor,
		PushAndPull,
		HoldTheDoor,
		JackSuperPushedOverTheGaps,
		JackCrossesTheCracks,
		MultiPushAcrossSpikes,
		WoodBlockPuzzle,
		HoldTheDoor2,
		SawdustToCoverSpikes,
		FireballIntro,
		StickySwitchIntro,
		BigStickySwitchPuzzle,
		TinyStickySwitchPuzzle,
		JackTutorial_Z,
		KahunaTutorial_Z,
		LagunaTutorial_Z,
		HadesMansion,
		HadesFrontLawn,
		GateToTheUnderworld,
	}
}
