using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEngine;

namespace Editor
{
    public class ScenumGenerator : EditorWindow
    {
        [MenuItem("Tools/Generate Scenum")]
        static void GenerateScenum()
        {
            var fileContents = new List<string>();
            fileContents.Add("// This file was generated by ScenumGenerator.cs. Do not edit!");
            fileContents.Add(
                "// Since Unity serializes enums as ints, do not expose this to the editor. This is meant to easily switch scenes by build index in code");
            fileContents.Add("public static class Scenum");
            fileContents.Add("{");
            fileContents.Add("\tpublic enum Scene");
            fileContents.Add("\t{");
            var sceneNumber = 0;
            foreach (var scene in EditorBuildSettings.scenes)
            {
                
                if (scene.enabled)
                {
                    var name = scene.path;
                    name = name.Remove(name.LastIndexOf('.'));
                    name = name.Remove(0, name.LastIndexOf('/') + 1);
                    name = String.Concat(name.Where(c => !Char.IsWhiteSpace(c)));
                    fileContents.Add($"\t\t{name} = {sceneNumber},");
                    sceneNumber += 1;
                }
            }

            fileContents.Add("\t}");
            fileContents.Add("}");
            var scriptPath = Application.dataPath + "/Scripts/Scenum.cs";
            File.WriteAllLines(scriptPath, fileContents);
            AssetDatabase.ImportAsset("Assets/Scripts/Scenum.cs");
            Debug.Log("Scenum Generated!");
        }
    }
}